import { defineType, defineField, defineArrayMember } from 'sanity'
import { BlockListItem } from '../components/BlockListItem'

export const page = defineType({
  name: 'page',
  title: 'Page',
  type: 'document',
  fields: [
    defineField({ name: 'title', type: 'string', validation: (Rule) => Rule.required() }),
    defineField({
      name: 'slug',
      type: 'slug',
      options: { source: 'title' },
      validation: (Rule) => Rule.required(),
    }),
    // Set by @sanity/document-internationalization — not hand-edited.
    defineField({ name: 'language', type: 'string', readOnly: true }),
    defineField({
      name: 'seoTitle',
      title: 'SEO title',
      description: 'The browser tab / search result title. Aim for under about 60 characters. Falls back to the site default if empty.',
      type: 'string',
      validation: (Rule) => Rule.max(70).warning('Search engines usually cut titles off past about 60 characters.'),
    }),
    defineField({
      name: 'seoDescription',
      title: 'SEO description',
      description: 'The summary shown under the title in search results. Aim for under about 160 characters. Falls back to the site default if empty.',
      type: 'text',
      rows: 3,
      validation: (Rule) => Rule.max(200).warning('Search engines usually cut descriptions off past about 160 characters.'),
    }),
    defineField({
      name: 'blocks',
      type: 'array',
      components: { item: BlockListItem },
      of: [
        defineArrayMember({ type: 'headerBlock' }),
        defineArrayMember({ type: 'heroBlock' }),
        defineArrayMember({ type: 'heroBackdropBlock' }),
        defineArrayMember({ type: 'heroImageOverlayCardBlock' }),
        defineArrayMember({ type: 'heroTextBlock' }),
        defineArrayMember({ type: 'sectionHeadlineBlock' }),
        defineArrayMember({ type: 'featureSplitBlock' }),
        defineArrayMember({ type: 'featureSplitDarkBlock' }),
        defineArrayMember({ type: 'fiftyFiftyBannerBlock' }),
        defineArrayMember({ type: 'stepsBlock' }),
        defineArrayMember({ type: 'featureGridBlock' }),
        defineArrayMember({ type: 'featureListBlock' }),
        defineArrayMember({ type: 'cardGridBlock' }),
        defineArrayMember({ type: 'logoCloudBlock' }),
        defineArrayMember({ type: 'testimonialCarouselBlock' }),
        defineArrayMember({ type: 'testimonialLargeBlock' }),
        defineArrayMember({ type: 'statsBandBlock' }),
        defineArrayMember({ type: 'pricingBlock' }),
        defineArrayMember({ type: 'bentoGridBlock' }),
        defineArrayMember({ type: 'mediaBlock' }),
        defineArrayMember({ type: 'faqAccordionBlock' }),
        defineArrayMember({ type: 'comparisonTableBlock' }),
        defineArrayMember({ type: 'caseStudyGridBlock' }),
        defineArrayMember({ type: 'ctaBannerBlock' }),
        defineArrayMember({ type: 'darkBannerBlock' }),
        defineArrayMember({ type: 'fullWidthSingleBlock' }),
        defineArrayMember({ type: 'horizontalScrollStackBlock' }),
        defineArrayMember({ type: 'footerBlock' }),
      ],
    }),
  ],
  preview: {
    select: { title: 'title', language: 'language' },
    prepare: ({ title, language }) => ({ title: `${title} (${language})` }),
  },
})
